import { Project, BOMNode, ProductionOrder, ProductTemplate, TemplateNode, Assignee } from '../types';
import { APP_CONFIG } from '../config/AppConfig';
import { recalculateNodeRollups } from './rollupCalculator';

export const DEMO_PROJECT_ID = APP_CONFIG.DEFAULT_PROJECT_ID;
export const DEMO_TEMPLATE_ID = APP_CONFIG.DEFAULT_TEMPLATE_ID;

export const DEMO_PROJECT: Project = {
  id: DEMO_PROJECT_ID,
  name: 'Tesla Model 3 82kWh Battery Pack',
  code: 'TSLA-M3-82KWH-BP',
  archetype: 'Structural EV Battery Pack (Gen 3 Long Range)',
  description: 'High-energy-density structural 82kWh lithium-ion battery pack with integrated liquid cooling, 2170 NMC cells, laser-welded busbars, and centralized BMS master unit.',
  rootNodeId: 'node-l1-pack',
  createdAt: '2026-08-01T08:00:00.000Z',
  updatedAt: '2026-08-28T14:30:00.000Z',
  isDefaultDemo: true,
  category: 'Electric Vehicle Propulsion / Energy Storage',
  targetOutputUnits: 500,
  templateId: DEMO_TEMPLATE_ID,
};

export const DEMO_ORDERS: ProductionOrder[] = [
  {
    id: 'ord-4587',
    orderNumber: 'ORD-4587',
    projectId: DEMO_PROJECT_ID,
    title: 'Batch LR-01 (North America Logistics)',
    customerName: 'Tesla Gigafactory Fremont — Assembly Line 2',
    batchQuantity: 5,
    completedUnits: 4,
    status: 'in_progress',
    priority: 'high',
    progress: 85,
    startDate: '2026-08-10',
    targetDate: '2026-09-05',
    notes: '85% overall completion. Modules 1-4 assembled and passing initial high-voltage isolation tests. Final tray enclosure sealing in progress.',
    highlightNote: '85% overall, On Track',
    assignedLead: APP_CONFIG.DEFAULT_ASSIGNEES[0], // Sarah Chen
    assignedTeam: [APP_CONFIG.DEFAULT_ASSIGNEES[0], APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    templateId: DEMO_TEMPLATE_ID,
  },
  {
    id: 'ord-4568',
    orderNumber: 'ORD-4568',
    projectId: DEMO_PROJECT_ID,
    title: 'Batch EU-Performance (Giga Berlin)',
    customerName: 'Tesla Gigafactory Berlin-Brandenburg',
    batchQuantity: 2,
    completedUnits: 1,
    status: 'urgent_delayed',
    priority: 'critical',
    progress: 60,
    startDate: '2026-08-15',
    targetDate: '2026-08-30',
    notes: 'Cell sorting line #2 reported calibration divergence during OCV spectrometry. Cell Assembly currently blocked pending QC re-certification.',
    highlightNote: '60% overall, Cell Assembly blocked',
    assignedLead: APP_CONFIG.DEFAULT_ASSIGNEES[1], // Marco Rossi
    assignedTeam: [APP_CONFIG.DEFAULT_ASSIGNEES[1], APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    templateId: DEMO_TEMPLATE_ID,
  },
  {
    id: 'ord-4540',
    orderNumber: 'ORD-4540',
    projectId: DEMO_PROJECT_ID,
    title: 'Prototype Batch Q3 Validation',
    customerName: 'Tesla Engineering Crash & Thermal Lab (Palo Alto)',
    batchQuantity: 1,
    completedUnits: 1,
    status: 'completed',
    priority: 'medium',
    progress: 100,
    startDate: '2026-08-01',
    targetDate: '2026-08-20',
    completedDate: '2026-08-19',
    notes: '100% finished. Passed helium leak testing, high-voltage hi-pot validation, and vibration shaker qualification tests without anomalies.',
    highlightNote: '100% finished & certified',
    assignedLead: APP_CONFIG.DEFAULT_ASSIGNEES[2], // Alex Miller
    assignedTeam: [APP_CONFIG.DEFAULT_ASSIGNEES[2], APP_CONFIG.DEFAULT_ASSIGNEES[3], APP_CONFIG.DEFAULT_ASSIGNEES[4]],
    templateId: DEMO_TEMPLATE_ID,
  },
];

// SVG Data URLs for clean visual whiteboxing previews
const SVG_ICONS = {
  pack: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%236366f1' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect width='16' height='20' x='4' y='2' rx='2'/><path d='M10 6h4'/><path d='m10 13 2 2 4-4'/></svg>",
  module: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%230ea5e9' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='2' y='6' width='20' height='12' rx='2'/><path d='M6 12h.01M10 12h.01M14 12h.01M18 12h.01'/></svg>",
  bms: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%23ec4899' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='4' y='4' width='16' height='16' rx='2'/><path d='M9 9h6v6H9z'/><path d='M9 1v3M15 1v3M9 20v3M15 20v3M1 9h3M1 15h3M20 9h3M20 15h3'/></svg>",
  thermal: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%2310b981' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z'/></svg>",
  enclosure: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%23f59e0b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z'/><path d='m3.3 7 8.7 5 8.7-5'/><path d='M12 22V12'/></svg>",
  cell: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%2338bdf8' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect width='16' height='10' x='4' y='7' rx='2'/><path d='M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2'/></svg>",
  weld: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 24 24' fill='none' stroke='%23f43f5e' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='m13 2 9 9-4 4-9-9Z'/><path d='m10 14-5 5'/><path d='m15 9-1 1'/></svg>",
};

const rawDemoNodes: BOMNode[] = [
  // LEVEL 1: End Item
  {
    id: 'node-l1-pack',
    projectId: DEMO_PROJECT_ID,
    parentId: null,
    title: 'Tesla Model 3 82kWh Structural Pack',
    code: 'TSLA-M3-82KWH-BP',
    level: 1,
    progress: 82,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[0], APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[0], // Sarah Chen
    image: SVG_ICONS.pack,
    status: 'in_progress',
    startDate: '2026-08-01',
    dueDate: '2026-09-15',
    batchQuantity: 1,
    unit: 'pack',
    notes: 'Structural battery pack integrating 4 high-voltage module blocks, full-span liquid ribbon cooling, and master BMS controller.',
    normHours: 175,
    weight: 175,
    orderIndex: 0,
  },

  // LEVEL 2: Major Modules / Assemblies
  {
    id: 'node-l2-modules',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l1-pack',
    title: '2170 Battery Module Array (4x Modules)',
    code: 'MOD-ARR-01',
    level: 2,
    progress: 75,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[1], APP_CONFIG.DEFAULT_ASSIGNEES[0]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[1], // Marco Rossi
    image: SVG_ICONS.module,
    status: 'delayed',
    startDate: '2026-08-05',
    dueDate: '2026-08-30', // < 2 days alert!
    batchQuantity: 4,
    unit: 'modules',
    notes: 'Four 96s46p cell brick modules forming the 400V DC high-voltage architecture.',
    normHours: 104,
    weight: 104,
    orderIndex: 0,
  },
  {
    id: 'node-l2-bms',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l1-pack',
    title: 'BMS Master Controller & Pyro Fuse',
    code: 'BMS-CTRL-01',
    level: 2,
    progress: 90,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[3], APP_CONFIG.DEFAULT_ASSIGNEES[4]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[3], // Elena Kovalenko
    image: SVG_ICONS.bms,
    status: 'in_progress',
    startDate: '2026-08-03',
    dueDate: '2026-09-02',
    batchQuantity: 1,
    unit: 'set',
    notes: 'Centralized Battery Management System with CAN-FD and redundant pyrotechnic disconnect safety circuit.',
    normHours: 18,
    weight: 18,
    orderIndex: 1,
  },
  {
    id: 'node-l2-thermal',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l1-pack',
    title: 'Thermal Management & Glycol Chiller Plate',
    code: 'THRM-PLT-01',
    level: 2,
    progress: 88,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[2], // Alex Miller
    image: SVG_ICONS.thermal,
    status: 'in_progress',
    startDate: '2026-08-04',
    dueDate: '2026-09-05',
    batchQuantity: 1,
    unit: 'system',
    notes: 'Extruded aluminum serpentine cooling ribbons with glycol/water loop capable of 15kW heat rejection during Supercharging.',
    normHours: 28,
    weight: 28,
    orderIndex: 2,
  },
  {
    id: 'node-l2-enclosure',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l1-pack',
    title: 'HV Enclosure & Penthouse Seal Assembly',
    code: 'ENC-PENT-01',
    level: 2,
    progress: 95,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[4], APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[4], // David Tanaka
    image: SVG_ICONS.enclosure,
    status: 'in_progress',
    startDate: '2026-08-02',
    dueDate: '2026-09-10',
    batchQuantity: 1,
    unit: 'tray',
    notes: 'Die-cast aluminum structural bottom tray with EPDM environmental gasket and high-strength steel top lid.',
    normHours: 25,
    weight: 25,
    orderIndex: 3,
  },

  // LEVEL 3: Sub-assemblies
  {
    id: 'node-l3-cell-bricks',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-modules',
    title: '2170 Cell Brick Assemblies (46 Bricks)',
    code: 'CELL-BRK-2170',
    level: 3,
    progress: 70,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[1], // Marco Rossi
    image: SVG_ICONS.cell,
    status: 'delayed',
    startDate: '2026-08-06',
    dueDate: '2026-08-29',
    batchQuantity: 46,
    unit: 'bricks',
    notes: '46 high-density cell matrix blocks with fire-retardant intumescent spacers.',
    normHours: 56,
    weight: 56,
    orderIndex: 0,
  },
  {
    id: 'node-l3-laser-grid',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-modules',
    title: 'Laser-Welded Current Collector Ribbon Grid',
    code: 'WELD-GRID-01',
    level: 3,
    progress: 85,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[0]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[0], // Sarah Chen
    image: SVG_ICONS.weld,
    status: 'in_progress',
    startDate: '2026-08-08',
    dueDate: '2026-09-01',
    batchQuantity: 8,
    unit: 'grids',
    notes: 'Precision stamped copper/aluminum collector plates with automated wire-bonding.',
    normHours: 48,
    weight: 48,
    orderIndex: 1,
  },
  {
    id: 'node-l3-bms-sensor',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-bms',
    title: 'BMS HV Sensor & Cell Tap Monitoring Board',
    code: 'BMS-HV-SEN',
    level: 3,
    progress: 92,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[3]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[3], // Elena Kovalenko
    image: SVG_ICONS.bms,
    status: 'in_progress',
    startDate: '2026-08-05',
    dueDate: '2026-09-02',
    batchQuantity: 4,
    unit: 'pcba',
    notes: 'Multi-channel ASIC voltage and temperature sense boards for millivolt-level accuracy.',
    normHours: 8,
    weight: 8,
    orderIndex: 0,
  },
  {
    id: 'node-l3-pyro-switch',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-bms',
    title: 'Pyrotechnic Battery Disconnect Switch',
    code: 'PYRO-DISC-01',
    level: 3,
    progress: 100,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[4]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[4], // David Tanaka
    image: SVG_ICONS.bms,
    status: 'completed',
    startDate: '2026-08-03',
    dueDate: '2026-08-22',
    batchQuantity: 1,
    unit: 'unit',
    notes: 'Sub-millisecond pyro safety disconnect triggered by collision accelerometer or overcurrent trip.',
    normHours: 10,
    weight: 10,
    orderIndex: 1,
  },
  {
    id: 'node-l3-cooling-snakes',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-thermal',
    title: 'Ribbon Cooling Channels & Snake Heat Sinks',
    code: 'COOL-SNK-01',
    level: 3,
    progress: 88,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[2], // Alex Miller
    image: SVG_ICONS.thermal,
    status: 'in_progress',
    startDate: '2026-08-06',
    dueDate: '2026-09-04',
    batchQuantity: 8,
    unit: 'ribbons',
    notes: 'Serpentine corrugated aluminum extrusion channels snaking between cell rows.',
    normHours: 16,
    weight: 16,
    orderIndex: 0,
  },
  {
    id: 'node-l3-dielectric-pu',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-thermal',
    title: 'Dielectric Gap Filler & Thermal Polyurethane',
    code: 'THERM-PU-01',
    level: 3,
    progress: 100,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[2],
    image: SVG_ICONS.thermal,
    status: 'completed',
    startDate: '2026-08-04',
    dueDate: '2026-08-25',
    batchQuantity: 20,
    unit: 'liters',
    notes: 'Thermally conductive potting compound providing structural adhesion and flame retardancy.',
    normHours: 12,
    weight: 12,
    orderIndex: 1,
  },
  {
    id: 'node-l3-alum-tray',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l2-enclosure',
    title: 'Die-Cast Aluminum Base Tray & Mounts',
    code: 'ALUM-TRAY-01',
    level: 3,
    progress: 95,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[4]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[4],
    image: SVG_ICONS.enclosure,
    status: 'in_progress',
    startDate: '2026-08-02',
    dueDate: '2026-09-08',
    batchQuantity: 1,
    unit: 'tray',
    notes: 'High-integrity aluminum casting with integral chassis mounting brackets.',
    normHours: 25,
    weight: 25,
    orderIndex: 0,
  },

  // LEVEL 4: Functional Blocks
  {
    id: 'node-l4-nmc-cells',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l3-cell-bricks',
    title: 'NMC 2170 Cylindrical Battery Cells (4,416 Cells)',
    code: 'CELL-NMC-2170',
    level: 4,
    progress: 65,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[1],
    image: SVG_ICONS.cell,
    status: 'delayed',
    startDate: '2026-08-07',
    dueDate: '2026-08-29',
    batchQuantity: 4416,
    unit: 'cells',
    notes: 'High-nickel cathode 2170 form-factor cylindrical cells with silicon-doped graphite anodes.',
    normHours: 42,
    weight: 42,
    orderIndex: 0,
  },
  {
    id: 'node-l4-matrix-holder',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l3-cell-bricks',
    title: 'Dielectric Cell Holder Matrix & Insulators',
    code: 'HLDR-MTX-01',
    level: 4,
    progress: 85,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[0]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[0],
    image: SVG_ICONS.cell,
    status: 'in_progress',
    startDate: '2026-08-06',
    dueDate: '2026-09-01',
    batchQuantity: 92,
    unit: 'halves',
    notes: 'Precision injection-molded polycarbonate flame-retardant cell spacing grid.',
    normHours: 14,
    weight: 14,
    orderIndex: 1,
  },
  {
    id: 'node-l4-busbar-tabs',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l3-laser-grid',
    title: 'Pure Copper Anode Collector Busbar Tabs',
    code: 'BUS-CU-01',
    level: 4,
    progress: 85,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[0]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[0],
    image: SVG_ICONS.weld,
    status: 'in_progress',
    startDate: '2026-08-09',
    dueDate: '2026-09-02',
    batchQuantity: 184,
    unit: 'plates',
    notes: 'Oxygen-free high conductivity (OFHC) copper stamped busbars with laser weld targets.',
    normHours: 48,
    weight: 48,
    orderIndex: 0,
  },
  {
    id: 'node-l4-mcu-can',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l3-bms-sensor',
    title: 'Microcontroller & CAN-FD Transceiver Node',
    code: 'MCU-CAN-01',
    level: 4,
    progress: 92,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[3]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[3],
    image: SVG_ICONS.bms,
    status: 'in_progress',
    startDate: '2026-08-06',
    dueDate: '2026-09-02',
    batchQuantity: 4,
    unit: 'boards',
    notes: 'Dual-core ASIL-D certified safety MCU with real-time fault detection and telemetry.',
    normHours: 8,
    weight: 8,
    orderIndex: 0,
  },
  {
    id: 'node-l4-micro-tubes',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l3-cooling-snakes',
    title: 'Extruded Micro-Channel Aluminum Tubes',
    code: 'MICRO-TUBE-01',
    level: 4,
    progress: 88,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[2],
    image: SVG_ICONS.thermal,
    status: 'in_progress',
    startDate: '2026-08-07',
    dueDate: '2026-09-03',
    batchQuantity: 32,
    unit: 'tubes',
    notes: 'Multi-port extruded aluminum cooling ribbons with interior flow turbulence fins.',
    normHours: 16,
    weight: 16,
    orderIndex: 0,
  },

  // LEVEL 5: Parts / Manufacturing Operations (Leaf nodes)
  {
    id: 'node-l5-ocv-sort',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-nmc-cells',
    title: 'Automated Impedance & OCV Spectrometry Sorting',
    code: 'OP-OCV-SORT',
    level: 5,
    progress: 55,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[1], APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[1],
    image: SVG_ICONS.cell,
    status: 'delayed',
    startDate: '2026-08-08',
    dueDate: '2026-08-29',
    batchQuantity: 4416,
    unit: 'tests',
    notes: 'Automated 4-point Kelvin probe testing sorting cells into 0.5mOhm matching capacity bins. Spectrometer #2 recalibration required.',
    normHours: 18,
    weight: 18,
    orderIndex: 0,
  },
  {
    id: 'node-l5-pnp-insert',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-nmc-cells',
    title: 'Cell Pick-and-Place Insertion into Matrix',
    code: 'OP-PNP-INS',
    level: 5,
    progress: 75,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[1]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[1],
    image: SVG_ICONS.cell,
    status: 'in_progress',
    startDate: '2026-08-10',
    dueDate: '2026-08-30',
    batchQuantity: 4416,
    unit: 'insertions',
    notes: 'High-speed robotic gantry inserting matched cells with alternating polarity into dielectric matrix.',
    normHours: 24,
    weight: 24,
    orderIndex: 1,
  },
  {
    id: 'node-l5-laser-weld',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-busbar-tabs',
    title: 'Automated High-Speed Laser Spot Welding (1,064nm)',
    code: 'OP-LASER-WELD',
    level: 5,
    progress: 80,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[0]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[0],
    image: SVG_ICONS.weld,
    status: 'in_progress',
    startDate: '2026-08-12',
    dueDate: '2026-09-01',
    batchQuantity: 8832,
    unit: 'welds',
    notes: 'Fiber laser scanner welding positive button tops and negative casing shoulders without thermal bleed.',
    normHours: 36,
    weight: 36,
    orderIndex: 0,
  },
  {
    id: 'node-l5-pull-test',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-busbar-tabs',
    title: 'Pull-Test & Weld Electrical Conductivity Verification',
    code: 'OP-PULL-TEST',
    level: 5,
    progress: 90,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[2]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[2],
    image: SVG_ICONS.weld,
    status: 'in_progress',
    startDate: '2026-08-14',
    dueDate: '2026-09-02',
    batchQuantity: 400,
    unit: 'samples',
    notes: 'Mechanical shear and pull force validation testing (min 35N spec) and micro-ohm resistance checks.',
    normHours: 12,
    weight: 12,
    orderIndex: 1,
  },
  {
    id: 'node-l5-fw-flash',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-mcu-can',
    title: 'BMS Firmware Flashing & CAN Bus Protocol Validation',
    code: 'OP-FW-FLASH',
    level: 5,
    progress: 92,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[3]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[3],
    image: SVG_ICONS.bms,
    status: 'in_progress',
    startDate: '2026-08-10',
    dueDate: '2026-09-02',
    batchQuantity: 4,
    unit: 'flashes',
    notes: 'Production firmware release v2026.8.2 flashed with cryptographically signed secure boot keys.',
    normHours: 8,
    weight: 8,
    orderIndex: 0,
  },
  {
    id: 'node-l5-he-leak',
    projectId: DEMO_PROJECT_ID,
    parentId: 'node-l4-micro-tubes',
    title: 'Helium Sniffer Leak Detection & Vacuum Pressure Test',
    code: 'OP-HE-LEAK',
    level: 5,
    progress: 88,
    assignees: [APP_CONFIG.DEFAULT_ASSIGNEES[4]],
    assignee: APP_CONFIG.DEFAULT_ASSIGNEES[4],
    image: SVG_ICONS.thermal,
    status: 'in_progress',
    startDate: '2026-08-11',
    dueDate: '2026-09-03',
    batchQuantity: 32,
    unit: 'tests',
    notes: 'Vacuum chamber pressurized to 2.5 bar with 10% Helium mix; threshold < 1.0E-5 mbar*l/s.',
    normHours: 16,
    weight: 16,
    orderIndex: 0,
  },
];

export const DEMO_NODES: BOMNode[] = recalculateNodeRollups(rawDemoNodes);

// Convert rawDemoNodes into a reusable Product Template with normHours
export const DEMO_TEMPLATES: ProductTemplate[] = [
  {
    id: DEMO_TEMPLATE_ID,
    name: 'Tesla Model 3 82kWh Battery Pack Archetype',
    code: 'TMPL-TSLA-M3-BP',
    archetype: 'Structural EV Battery Pack (Gen 3 Long Range)',
    description: 'Master manufacturing blueprint for 82kWh liquid-cooled structural pack with 2170 cells and integrated BMS.',
    category: 'Electric Vehicle Propulsion',
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-28T14:30:00.000Z',
    isBuiltIn: true,
    nodes: rawDemoNodes.map((n) => ({
      id: `tmpl-node-${n.id}`,
      parentId: n.parentId ? `tmpl-node-${n.parentId}` : null,
      title: n.title,
      code: n.code,
      level: n.level,
      defaultDurationDays: 14,
      defaultBatchQuantity: n.batchQuantity,
      unit: n.unit,
      normHours: n.normHours || 10,
      weight: n.normHours || 10,
      notes: n.notes,
      image: n.image,
      orderIndex: n.orderIndex,
      suggestedRole: n.assignees?.[0]?.role || n.assignee?.role || 'Lead Specialist',
    })),
  },
  {
    id: 'tmpl-dual-motor-inverter',
    name: 'Dual-Motor Silicon Carbide (SiC) Inverter',
    code: 'TMPL-SIC-INV-400V',
    archetype: 'High-Power Traction Inverter Module',
    description: '800V/400V dual-motor silicon carbide traction inverter template with direct liquid cooling and gate drivers.',
    category: 'Power Electronics',
    createdAt: '2026-08-05T10:00:00.000Z',
    updatedAt: '2026-08-20T12:00:00.000Z',
    isBuiltIn: true,
    nodes: [
      {
        id: 'tmpl-inv-l1',
        parentId: null,
        title: 'Dual-Motor SiC Traction Inverter 350kW',
        code: 'INV-SIC-350KW',
        level: 1,
        defaultDurationDays: 30,
        defaultBatchQuantity: 1,
        unit: 'unit',
        normHours: 75,
        weight: 75,
        orderIndex: 0,
        suggestedRole: 'Chief Power Architect',
        notes: 'High-efficiency 350kW continuous traction power inverter with dual independent motor channels.',
      },
      {
        id: 'tmpl-inv-l2-sic',
        parentId: 'tmpl-inv-l1',
        title: 'SiC MOSFET Power Stage Module (6-Pack)',
        code: 'SIC-MOD-01',
        level: 2,
        defaultDurationDays: 20,
        defaultBatchQuantity: 6,
        unit: 'modules',
        normHours: 45,
        weight: 45,
        orderIndex: 0,
        suggestedRole: 'Lead Power Electronics Engineer',
        notes: '1200V / 600A automotive qualified SiC MOSFET half-bridge power modules.',
      },
      {
        id: 'tmpl-inv-l2-gate',
        parentId: 'tmpl-inv-l1',
        title: 'Galvanically Isolated Gate Driver PCBA',
        code: 'GATE-DRV-01',
        level: 2,
        defaultDurationDays: 15,
        defaultBatchQuantity: 2,
        unit: 'boards',
        normHours: 30,
        weight: 30,
        orderIndex: 1,
        suggestedRole: 'BMS Firmware Lead',
        notes: 'High-speed 5kV isolated gate drivers with active Miller clamp and desaturation fault protection.',
      },
      {
        id: 'tmpl-inv-l3-cap',
        parentId: 'tmpl-inv-l2-sic',
        title: 'Low-Inductance DC Link Film Capacitor Block',
        code: 'DC-CAP-600UF',
        level: 3,
        defaultDurationDays: 10,
        defaultBatchQuantity: 1,
        unit: 'block',
        normHours: 25,
        weight: 25,
        orderIndex: 0,
        suggestedRole: 'Quality & Thermal Specialist',
        notes: 'Custom polypropylene film capacitor with integrated copper planar busbar.',
      },
      {
        id: 'tmpl-inv-l3-chiller',
        parentId: 'tmpl-inv-l2-sic',
        title: 'Direct-Pin Fin Liquid Cold Plate',
        code: 'COLD-PLT-PIN',
        level: 3,
        defaultDurationDays: 12,
        defaultBatchQuantity: 1,
        unit: 'chiller',
        normHours: 20,
        weight: 20,
        orderIndex: 1,
        suggestedRole: 'Lead Automation Engineer',
        notes: 'Micro pin-fin copper cooler baseplate directly interfacing SiC substrate.',
      },
    ],
  },
];
